server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://192.168.245.133:3306/cloud_order?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: manager
    password: Admin123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SZ

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#  httpclient:
#    enabled: true
#    max-connections: 200
#    max-connections-per-route: 50
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8089/eureka
    #register-with-eureka: true
    #fetch-registry: true
#usersevice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
